### PR TITLE
Upgraded Retrofit, Butterknife & added rxjava2 changes

### PR DESCRIPTION
**Pull request by RajuSE**
@jpotts18 I had:
Upgraded Retrofit to v:2.1.0
Upgraded Butterknife to v:8.4.0 & 
Added rxjava2 changes.

### CODE REVIEW

**Comment by RajuSE** [comment]
I'm interested in getting your thoughts on this

**Comment by jpotts18** [comment]
Thanks for you work @RajuSE! Before we merge this here are some of my concerns: 

* This repository uses branches to teach the concepts of MVP. We would need to update all of the branches that are used to build to `master` so the changes would make sense. 

* We would need to update the [Youtube video](https://www.youtube.com/watch?v=qE4DEwrK2N4) that goes along with this repository. 

It may be better to create a different branch called `master-2`. We could reference `master-2` in the documentation and tell people this shows the most up-to-date libraries and enhancements. What do you think?

**Comment by RajuSE** [comment]
Creating master-2 sounds like a great thought! Specially new xyz libraries are going to come upcoming time.. Core idea should remain understandable. Only concern I see is we have to sync up master-2 with base when required, which is fine. I think we're good to go!

**Comment by RajuSE** [comment]
Only darkside I see we have to sync up master-2 with base when required, which i think is fine.

**Comment by jpotts18** [comment]
Alight I'm going to merge this into `master-2`. I'll add documentation to the README.md

**Comment by jpotts18** [comment]
I gave you a shout out as well! Thanks!

**Comment by RajuSE** [comment]
No! You Rock👍!! Thanks!

**Pull request merged**
